### ISSUE TITLE
USB-C to hdmi not working

### ISSUE THREAD

**Issue by J0uj0u** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh#19]
Hello, did you try to use usb-c port for external monitor ? I didn't have exactly the same PC but your configuration work well exept that. It was only to know if it work for you
Thank you

**Comment by whatnameisit** [comment]
I don't have the cable so I can't test. I don't know much about the USB-C to HDMI mechanism, but the framebuffer has to be enabled for any display. You can configure the PciRoot(0x0)/Pci(0x2,0x0) dictionary under DeviceProperties. Con0 is internal LVDS, Con1 is disabled by setting Index as -1, Con2 is HDMI, and Con3 is disabled by the chosen ig-platform-id.
This may help: https://www.tonymacx86.com/threads/guide-general-framebuffer-patching-guide-hdmi-black-screen-problem.269149/

**Comment by J0uj0u** [comment]
Hi,
Sorry for the delay, finaly my laptop not support hdmi with usb-c.
Hdmi port work well.
Ty
