### ISSUE TITLE
Cant install any version

### ISSUE THREAD

**Issue by dmatyid** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh#20]
Hi!
I have the exact ASUS model that’s specified, but I can’t get opencore working no matter what I do.
I followed the dortania OC guide, created my own EFI, didn’t work.
Next I tried this EFI, still can’t install.

On Catalina when I get to the internet recovery mode I get this message: ‘ The macOS Installation Couldn’t Be Completed’

Next I tried Mojave, when I get to the internet recovery mode I can’t get get past the main screen, like the Utilites is frozen. Mouse works fine, I can interact with any other app, I can type the WiFi password in, but when I try to click Reinstall MacOS it does nothing.

I tried booting with only the essential kexts, still the same error.

Can anyone help me?
Thanks in advance!

**Comment by whatnameisit** [comment]
Hi. Make sure you download and mount the official installation image, and mount the whole installation instead of just the recovery. I remember reading in the Dortania guide that installation via the Wi-Fi is not recommended.
I just tested my EFI on new installation and it works fine.

**Comment by dmatyid** [comment]
I deleted everything and did an nvram reset, everything works fine on big sur. Thanks for the amazing work!
