### ISSUE TITLE
Clover broken for installing and booting Catalina 10.15.3

### ISSUE THREAD

**Issue by Krakenko007** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh#21]
hi, I got stuck on the language selection screen. When I click the next button, it doesn't do anything. I've looked up this issue, but nothing seemed to help, and by the way I'm using the hackintoshzone installation guide. I've replaced the clover efi (clover,boot) files from you (https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh).
I've tried are Clover, Unibeast, many YouTube tutorials, the guide on this website. None of those seemed to have worked for me
Where is the problem. I have alike pc specification.  ASUS VivoBook 15 X510UF (Intel(R) Core(TM) i5-8250U) uhd620+nvidia mx130.
Thank you

**Comment by whatnameisit** [comment]
Does disabling NVidia graphics with -wegnoegpu help?
What version of OS are you trying to install?
You'd also want to study OpenCore with the official Configuration.pdf and guides found at Dortania. Clover won't work on Big Sur.

**Comment by whatnameisit** [comment]
What bootloader are you using?
Have you actually read the guides I pointed at?
Enable VT-D and IVT. Check you have DisableIOMapper quirk enabled on OpenCore or set dart=0 on Clover.
No idea what the region setting menu is.

**Comment by Krakenko007** [comment]
i using  type bios 3O3 
when vtd was off I could set the language maybe only luck?
![IMG_4306](https://user-images.githubusercontent.com/75023105/100397197-ba852a80-3048-11eb-9291-68834665a3a4.jpg)
Specifically, there is a problem, I can't log in because in the background is the apple logo, which does not allow me to log in.
i dont know,where is problem :/

**Comment by whatnameisit** [comment]
You would want to switch to OpenCore because Clover is becoming deprecated, and as of now my Clover configuration does not support recent Clover or Big Sur.
When you switch to OpenCore:
Turn VT-D on because it is disabled with DisableIOMapper. IVT does not have negative effect on macOS to my knowledge.
Read Configuration.pdf and Dortania guides.
Then boot macOS using OpenCore.

**Comment by Krakenko007** [comment]
solved. Finally, I successfully installed cataline with an open core. finally you need to turn on vtd. even though I worked with it all day, it was worth it! Finally, I would like to remind you that there is no need to change the wifi card (intel). just install itlwm.kexts and heliport. Thanks for help :)

**Comment by whatnameisit** [comment]
I will drop support for Clover. For the last time, read the guides I said you should.
You never needed to disable VT-D since Clover. Itlwm is for those with on-board Wi-Fi card. Limited continuity features.
