### ISSUE TITLE
Have you tried upgrading to Big Sur?

### ISSUE THREAD

**Issue by ArestenkoA** [whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh#23]
Hi! Have you tried upgrading to Big Sur?
My laptop configuration:
In the system configuration, my laptop is labeled: Asus vivobook x510unr, but on the bottom of the laptop it says - s510un
i7-8550u
Nvidia mx150
16gb ddr4
Intel dual band wireless ac-8265

In terms of specifications, our laptops are quite similar, but are they?
How important is the processor difference between the i5 and i7 to the operating system? Or more importantly, what generation are they? In this case, they are both generations of Kaby lake.

The question is whether you have updated to Big Sur. And can I take your files as a basis for a hackintosh for Big Sur using the OpenCore loader?

**Comment by whatnameisit** [comment]
https://github.com/whatnameisit/Asus-Vivobook-X510UA-BQ490-Catalina-10.15.7-Hackintosh/issues/22
